# Generated by Django 4.2 on 2023-05-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(default='None', max_length=255)),
                ('reorderpoint', models.CharField(default='None', max_length=255)),
                ('brand', models.CharField(default='None', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expirationdate', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
